langchain4j.open-ai.chat-model.api-key=2cae583e197c41aa860c0bce2ff6e97c.RXWWVx0LdxNhlDGv
langchain4j.open-ai.chat-model.model-name=glm-5.1
langchain4j.open-ai.chat-model.base-url=https://open.bigmodel.cn/api/paas/v4

langchain4j.open-ai.streaming-chat-model.api-key=2cae583e197c41aa860c0bce2ff6e97c.RXWWVx0LdxNhlDGv
langchain4j.open-ai.streaming-chat-model.model-name=glm-5.1
langchain4j.open-ai.streaming-chat-model.base-url=https://open.bigmodel.cn/api/paas/v4

server.port=28688

spring.data.redis.host=localhost
spring.data.redis.port=6379
