langchain4j.open-ai.chat-model.api-key=73cf78e3f6a94f5e966ea66b2121394d.ZMr3QcCCvKxjdqAP
langchain4j.open-ai.chat-model.model-name=glm-5.1
langchain4j.open-ai.chat-model.base-url=https://open.bigmodel.cn/api/paas/v4

langchain4j.open-ai.streaming-chat-model.api-key=73cf78e3f6a94f5e966ea66b2121394d.ZMr3QcCCvKxjdqAP
langchain4j.open-ai.streaming-chat-model.model-name=glm-5.1
langchain4j.open-ai.streaming-chat-model.base-url=https://open.bigmodel.cn/api/paas/v4

server.port=28688

spring.data.redis.host=localhost
spring.data.redis.port=6379
