spring:
  datasource:
    url: jdbc:mysql://localhost:3306/llmstudy?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: tt
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: llmstudy
  ai:
    chat:
      memory:
        repository:
          jdbc:
            platform: mysql
            initialize-schema: always
    zhipuai:
      api-key: 73cf78e3f6a94f5e966ea66b2121394d.ZMr3QcCCvKxjdqAP
      chat:
        options:
          model: glm-5.1

server:
  port: 28688
