spring:
  application:
    name: rag
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
  datasource:
    url: ${PG_URL:jdbc:postgresql://localhost:5433/rag_test}
    username: ${PG_USERNAME:pgvector}
    password: ${PG_PASSWORD:}
  ai:
    zhipuai:
      api-key: ${ZHIPU_API_KEY:}
      embedding:
        options:
          model: ${RAG_EMBEDDING_MODEL:embedding-3}
          dimensions: ${RAG_EMBEDDING_DIMENSIONS:2048}
      chat:
        options:
          model: ${RAG_CHAT_MODEL:glm-4.5-Air}
    vectorstore:
      pgvector:
        # 向量索引类型
        index-type: NONE
        # 距离度量，余弦值
        distance-type: COSINE_DISTANCE
        # 向量维度
        dimensions: 2048
        # 批量处理大小
        max-document-batch-size: 9
        # 启动时是否自动创建表
        initialize-schema: true
        # 创建的表名
        table-name: vector_st
server:
  port: ${SERVER_PORT:28691}
