spring:
  application:
    name: pro-rag
  elasticsearch:
    uris: http://localhost:9200
  datasource:
    url: jdbc:postgresql://localhost:5433/rag_test
    username: pgvector
    password: pgvector
  ai:
    zhipuai:
      api-key: 73cf78e3f6a94f5e966ea66b2121394d.ZMr3QcCCvKxjdqAP
      embedding:
        options:
          model: embedding-3
          dimensions: 2048
      chat:
        options:
          model: glm-4.5-Air
    vectorstore:
      pgvector:
        # 向量索引类型
        index-type: NONE
        # 距离度量，余弦值
        distance-type: COSINE_DISTANCE
        # 向量维度
        dimensions: 2048
        # 批量处理大小
        max-document-batch-size: 9
        # 启动时是否自动创建表
        initialize-schema: true
        # 创建的表名
        table-name: pro_vector_st
server:
  port: 28689

# 文件上传目录
pro-rag:
  upload-dir: ./pro-rag-files
  generated-dir: ./pro-rag-generated
