spring:
  application:
    name: functioncall
  ai:
    zhipuai:
      api-key: 73cf78e3f6a94f5e966ea66b2121394d.ZMr3QcCCvKxjdqAP
      chat:
        options:
          model: glm-4.5-Air

server:
  port: 28688
